import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToasterProvider from "../providers/toastprovider";
import photo from "../../public/bg.jpg";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="font-cyberpunk my-20 mx-20"
        style={{
          height: "100vh",
          backgroundImage: `url(${photo.src})`,
          backgroundSize: "cover",
          backgroundPosition: "center",
          backgroundColor: "rgba(0, 0, 0, 0.5)", // Set the opacity here (0.5 is 50% opacity)
          backgroundBlendMode: "multiply", // Apply blend mode for soft transition
        }}
      >
        <ToasterProvider />
        {children}
      </body>
    </html>
  );
}
